### ISSUE TITLE
All features tracking list

### ISSUE THREAD

**Issue by williamhCode** [williamhCode/neogui#2]
- [x] add braille rendering
- [x] variable spacing between lines
- [x] add box drawing chars (all box drawing + box elements implemented)
- [x] add command-line/startup options
- [x] add input ime (have to fix this first - https://github.com/libsdl-org/SDL/issues/10486)
- [x] add emoji rendering
- [x] add default glyph fallback for glyphs not found in guifont
- [x] add ligatures
- [ ] remember window size
- [ ] hide cursor when inputting (sdl explodes, so hold back for now)
- [ ] add debug mode (window and frame rate information)
- [ ] buffer specific font size
- [ ] detachable sessions
- [ ] proper logging (implement stacktrace and levels) or maybe not depends

**Comment by williamhCode** [comment]
- [ ] add ligatures
- [ ] add input ime (have to fix this first - https://github.com/libsdl-org/SDL/issues/10486)
- [ ] hide cursor when inputting (sdl explodes, so hold back for now)
- [ ] buffer specific font size
- [ ] different toolbar color
- [ ] proper logging (implement stacktrace and levels) or maybe not depends
