### ISSUE TITLE
All issues tracking list

### ISSUE THREAD

**Issue by williamhCode** [williamhCode/neogui#3]
- [ ] Unpredictable (purple) flickering when resizing/switching windows
- [ ] Modifiers are sticky when switching focus and holding mod at the same time (only happens when invoked with Logitech mouse macro??) - https://github.com/libsdl-org/SDL/issues/10934
- [ ] Titlebar becomes weird after fullscreen for borderless
